/* fw-firebase.jsx — Firebase/Firestore real-time sync for Freya's World
   Architecture: one Firestore document per family code.
   Anti-loop: _fbSource ref prevents Firestore updates triggering re-saves.
   Debounce: 1200ms after last local change before writing to Firestore.
*/
const { useState: useStateFB, useEffect: useEffectFB, useRef: useRefFB } = React;

/* ---------- localStorage keys ---------- */
const FB_CFG_KEY  = 'fw_fbconfig';
const FB_FAM_KEY  = 'fw_famcode';

/* ---------- helpers ---------- */
function fbLoadConfig()     { try { return JSON.parse(localStorage.getItem(FB_CFG_KEY)||'null'); } catch { return null; } }
function fbSaveConfig(c)    { localStorage.setItem(FB_CFG_KEY, JSON.stringify(c)); }
function fbLoadFamily()     { return localStorage.getItem(FB_FAM_KEY) || ''; }
function fbSaveFamily(code) { localStorage.setItem(FB_FAM_KEY, code); }
// CSPRNG-based, 12 chars ≈ 62 bits entropy. Replaces the old Math.random()
// 6-char version, which was both short and not cryptographically random.
// NOTE: this only protects codes generated from now on. A family code
// generated by the old function and already shared/synced is not made
// safer retroactively — see CLIENT-CHANGES-REQUIRED.md §3.
function fbGenCode() {
  const bytes = new Uint8Array(9);
  crypto.getRandomValues(bytes);
  return Array.from(bytes, b => b.toString(36)).join('').toUpperCase().slice(0, 12);
}

/* ---------- Firebase singleton ---------- */
let _db = null;
let _storage = null;
let _authReady = null; // Promise<firebase.User|null> — resolves once anon sign-in completes
function fbInit(config) {
  try {
    if (!window.firebase) return null;
    if (!firebase.apps.length) firebase.initializeApp(config);
    _db = firebase.firestore();
    try { _storage = firebase.storage(); } catch(e) { console.error('Firebase Storage init:', e); _storage = null; }

    // Only kick off anonymous sign-in ONCE per page load. fbInit() gets
    // called from multiple places (wizard's testConnect, then fbConnect
    // after finish()) — calling signInAnonymously() again before the first
    // call's session has persisted risks the SDK creating a SECOND, different
    // anonymous account. That would silently orphan the members/{uid} doc
    // created under the first uid, causing permission-denied on every
    // subsequent read even though the rules and membership doc are correct.
    if (!_authReady) {
      _authReady = firebase.auth().currentUser
        ? Promise.resolve(firebase.auth().currentUser)
        : firebase.auth().signInAnonymously()
            .then(cred => cred.user)
            .catch(e => { console.error('Anonymous auth failed:', e); return null; });
    }

    return _db;
  } catch(e) { console.error('Firebase init:', e); return null; }
}
function fbAuthReady() { return _authReady || Promise.resolve(null); }
function fbGetDb() { return _db; }
function fbGetStorage() { return _storage; }
function fbDoc(familyCode) { return _db && _db.collection('families').doc(familyCode); }

/* ---------- Upload a File/Blob to Cloud Storage → resolves to a public downloadURL ---------- */
function fbUploadFile(familyCode, file, kind) {
  return new Promise((resolve, reject) => {
    if (!_storage) { reject(new Error('Storage not initialised')); return; }
    const ext = (file.name && file.name.includes('.')) ? file.name.split('.').pop() : (kind === 'video' ? 'mp4' : kind === 'audio' ? 'webm' : 'jpg');
    const path = `families/${familyCode}/evidence/${Date.now()}_${Math.random().toString(36).slice(2,8)}.${ext}`;
    const ref = _storage.ref().child(path);
    const task = ref.put(file);
    task.on('state_changed',
      null,
      (err) => reject(err),
      async () => {
        try { resolve(await task.snapshot.ref.getDownloadURL()); }
        catch(e) { reject(e); }
      }
    );
  });
}

/* ---------- Serialise app state for Firestore ---------- */
function stateToFs(s) {
  return {
    missions:    s.missions.map(m => ({ ...m })),
    stars:       s.stars,
    progress:    s.progress,
    wallet:      s.wallet.slice(0, 30),   // cap to 30 recent
    portfolio:   s.portfolio.slice(0, 40),
    submissions: s.submissions.slice(0, 30),
    rewards:     s.rewards.map(r => ({ ...r })),
    profile:     s.profile,
    planDone:    [...s.planDone],          // Set → Array
    room:        s.room || { owned: [], placed: {} },  // Freya's Room: item IDs only — art stays client-side
    // fun layer — streak, weekly loot box, sticker album, mascot outfit (IDs only)
    streak:      s.streak || { count: 0, best: 0, lastDay: '' },
    lootbox:     s.lootbox || { week: '', done: 0, lastOpen: '' },
    stickers:    (s.stickers || []).slice(0, 300),
    mascotFit:   s.mascotFit || { owned: [], worn: {} },
    updatedAt:   Date.now(),
  };
}
function fsToState(d) {
  return {
    missions:    d.missions    || [],
    stars:       d.stars       ?? 145,
    progress:    d.progress    || {},
    wallet:      d.wallet      || [],
    portfolio:   d.portfolio   || [],
    submissions: d.submissions || [],
    rewards:     d.rewards     || null,   // null = keep seed
    profile:     d.profile     || null,   // null = keep default
    planDone:    new Set(d.planDone || []),
    room:        d.room        || null,   // null = keep local (older docs have no room field)
    streak:      d.streak      || null,   // null = keep local (pre-fun-update docs)
    lootbox:     d.lootbox     || null,
    stickers:    d.stickers    || null,
    mascotFit:   d.mascotFit   || null,
  };
}

/* ---------- Setup wizard (shown inside Parent Settings) ---------- */
function FirebaseSetupWizard({ onDone }) {
  const [step, setStep] = useStateFB(1);
  const [apiKey, setApiKey] = useStateFB('');
  const [projectId, setProjectId] = useStateFB('');
  const [appId, setAppId] = useStateFB('');
  const [familyCode, setFamilyCode] = useStateFB(fbGenCode);
  const [busy, setBusy] = useStateFB(false);
  const [err, setErr] = useStateFB('');

  const inp = { width: '100%', border: '1.5px solid var(--accent-soft)', borderRadius: 12,
    padding: '10px 12px', font: 'inherit', fontSize: 13, color: 'var(--ink)', background: 'var(--surface)', outline: 'none', marginTop: 5 };

  const testConnect = async () => {
    if (!apiKey.trim() || !projectId.trim()) { setErr('ต้องกรอก API Key และ Project ID'); return; }
    setBusy(true); setErr('');
    try {
      const cfg = { apiKey: apiKey.trim(), projectId: projectId.trim(),
        authDomain: projectId.trim() + '.firebaseapp.com',
        storageBucket: projectId.trim() + '.firebasestorage.app',
        appId: appId.trim() || undefined };
      const db = fbInit(cfg);
      if (!db) throw new Error('Firebase SDK not ready');
      // NOTE: previously this wrote a throwaway doc to `_test/ping` to verify
      // the connection. Under the new rules, every path not explicitly
      // matched is denied — that write would now always fail even with a
      // correct config. Verifying anonymous auth resolves is a valid proxy:
      // if the API key/project are wrong, signInAnonymously() rejects too.
      const user = await fbAuthReady();
      if (!user) throw new Error('เชื่อมต่อไม่ได้ (auth ไม่สำเร็จ) — ตรวจสอบว่าเปิด Anonymous sign-in ใน Firebase Console แล้ว');
      fbSaveConfig(cfg);
      setStep(2);
    } catch(e) { setErr('เชื่อมต่อไม่ได้: ' + e.message.slice(0,80)); }
    setBusy(false);
  };

  const finish = async () => {
    const code = familyCode.trim().toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,10) || fbGenCode();
    // Under the new rules, families/{code} is unreadable/unwritable until a
    // members/{uid} doc exists for the signed-in user. Must await this
    // BEFORE saving/using the code, or the very first fbDoc(code) read in
    // fw-data.jsx will be denied (race condition if this isn't awaited).
    try {
      setBusy(true);
      const user = await fbAuthReady();
      if (!user) throw new Error('ไม่พบผู้ใช้ที่ signed in — เชื่อมต่อ Firebase ใหม่อีกครั้ง');
      await _db.collection('families').doc(code)
        .collection('members').doc(user.uid)
        .set({ joinedAt: Date.now() });
    } catch(e) {
      setBusy(false);
      setErr('เข้าร่วมครอบครัวไม่สำเร็จ: ' + e.message.slice(0,80));
      return;
    }
    setBusy(false);
    fbSaveFamily(code);
    onDone(code);
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
      {step === 1 && <>
        <div className="fb-hint">
          📋 <b>ขั้นตอน:</b><br/>
          1. ไป <b>console.firebase.google.com</b><br/>
          2. สร้าง Project → เปิด <b>Firestore Database</b> (Build → Firestore Database → Create database)<br/>
          3. เปิด <b>Storage</b> ด้วย (Build → Storage → Get started) — ใช้เก็บรูป/วิดีโอ/เสียงที่เฟรยาส่งงาน<br/>
          4. เปิด <b>Authentication → Sign-in method → Anonymous</b> แล้วกด Enable (จำเป็น — ไม่เปิดจะ sync ไม่ได้)<br/>
          5. Project Settings → Web App → คัดลอก <b>apiKey</b> และ <b>projectId</b><br/>
          6. วาง rules ด้านล่างนี้ที่ <b>Firestore → Rules</b> และ <b>Storage → Rules</b> แทนค่าเริ่มต้น (ห้ามใช้ "test mode" — มันเปิดให้ทุกคนอ่าน/เขียนได้โดยไม่ auth และหมดอายุแบบไม่เตือนใน 30 วัน)
        </div>
        <label style={{ fontSize: 12.5, fontWeight: 700, color: 'var(--ink)' }}>
          API Key
          <input style={inp} value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder="AIzaSy..." />
        </label>
        <label style={{ fontSize: 12.5, fontWeight: 700, color: 'var(--ink)' }}>
          Project ID
          <input style={inp} value={projectId} onChange={e=>setProjectId(e.target.value)} placeholder="freyaworld-xxxxx" />
        </label>
        <label style={{ fontSize: 12.5, fontWeight: 700, color: 'var(--ink)' }}>
          App ID <span style={{ fontWeight: 400, color: 'var(--ink-soft)' }}>(ไม่บังคับ)</span>
          <input style={inp} value={appId} onChange={e=>setAppId(e.target.value)} placeholder="1:xxxxx:web:xxxxx" />
        </label>
        {err && <div style={{ color: '#d4516b', fontSize: 12, fontWeight: 600 }}>{err}</div>}
        <button className="btn block" disabled={busy} onClick={testConnect}>
          {busy ? '⏳ กำลังทดสอบ...' : '✅ ทดสอบ & บันทึก'}
        </button>
        <details style={{ fontSize: 11.5, color: 'var(--ink-soft)' }}>
          <summary style={{ cursor: 'pointer', fontWeight: 700, color: 'var(--accent-deep)' }}>📜 Firestore Rules (วางที่ Build → Firestore Database → Rules)</summary>
          <pre style={{ background: '#1e1e1e', color: '#d4d4d4', borderRadius: 10, padding: '10px 12px', fontSize: 10.5, overflowX: 'auto', marginTop: 6 }}>{`rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    function isMember(familyCode) {
      return request.auth != null &&
        exists(/databases/$(database)/documents/families/$(familyCode)/members/$(request.auth.uid));
    }
    match /families/{familyCode} {
      allow read, write: if isMember(familyCode);
      match /members/{uid} {
        allow read: if isMember(familyCode);
        allow create: if request.auth != null && request.auth.uid == uid;
        allow delete: if isMember(familyCode);
        allow update: if false;
      }
    }
    match /{document=**} {
      allow read, write: if false;
    }
  }
}`}</pre>
          <div style={{ marginTop: 4 }}>⚠️ ห้ามเลือก "Start in test mode" — โหมดนั้นเปิดให้ทุกคนอ่าน/เขียนได้โดยไม่ต้อง auth และหมดอายุเงียบ ๆ ใน 30 วัน วาง rules ด้านบนนี้แทนตั้งแต่ตอนสร้าง database</div>
        </details>
        <details style={{ fontSize: 11.5, color: 'var(--ink-soft)' }}>
          <summary style={{ cursor: 'pointer', fontWeight: 700, color: 'var(--accent-deep)' }}>📜 Storage Rules (วางที่ Build → Storage → Rules)</summary>
          <pre style={{ background: '#1e1e1e', color: '#d4d4d4', borderRadius: 10, padding: '10px 12px', fontSize: 10.5, overflowX: 'auto', marginTop: 6 }}>{`rules_version = '2';
service firebase.storage {
  match /b/{bucket}/o {
    match /families/{familyCode}/evidence/{fileName} {
      allow read, write: if request.auth != null &&
        firestore.exists(
          /databases/(default)/documents/families/$(familyCode)/members/$(request.auth.uid)
        );
    }
    match /{allPaths=**} {
      allow read, write: if false;
    }
  }
}`}</pre>
          <div style={{ marginTop: 4 }}>ไฟล์รูป/วิดีโอ/เสียงของเฟรยาถูกป้องกันด้วย rules นี้ — คนที่ไม่ได้เป็นสมาชิกครอบครัว (ไม่มี members doc) เข้าไม่ได้เลย แม้จะรู้ projectId</div>
        </details>
      </>}
      {step === 2 && <>
        <div style={{ background: 'var(--surface-2)', borderRadius: 16, padding: 16, textAlign: 'center' }}>
          <div style={{ fontSize: 11.5, color: 'var(--ink-soft)', marginBottom: 4 }}>รหัสครอบครัวของคุณ · Family Code</div>
          <div style={{ fontFamily: 'monospace', fontSize: 30, fontWeight: 800, letterSpacing: 5, color: 'var(--accent-deep)' }}>{familyCode}</div>
          <div style={{ fontSize: 10.5, color: 'var(--ink-soft)', marginTop: 4 }}>📸 บันทึกไว้ด้วย — ใช้บนทุกเครื่อง</div>
        </div>
        <div style={{ fontSize: 12.5, color: 'var(--ink)' }}>หรือใส่รหัสที่มีอยู่แล้ว (ถ้าตั้งไว้เครื่องอื่นแล้ว):</div>
        <input style={inp} value={familyCode} onChange={e=>setFamilyCode(e.target.value.toUpperCase())} placeholder="เช่น A3KF92" maxLength={10} />
        <button className="btn block" onClick={finish}>🚀 เริ่ม Sync!</button>
      </>}
    </div>
  );
}

/* ---------- Sync status badge (shown in header) ---------- */
function FbStatusBadge({ status }) {
  const map = { idle:'⚪', connecting:'🟡', synced:'🟢', error:'🔴', offline:'⚪' };
  const label = { idle:'offline', connecting:'connecting…', synced:'synced', error:'error', offline:'offline' };
  if (status === 'idle' || status === 'offline') return null;
  return (
    <span style={{ fontSize: 10, fontWeight: 700, display: 'inline-flex', alignItems: 'center', gap: 3,
      background: 'rgba(255,255,255,0.22)', padding: '2px 8px', borderRadius: 999, color: '#fff' }}>
      {map[status]} {label[status]}
    </span>
  );
}

Object.assign(window, { fbInit, fbGetDb, fbGetStorage, fbUploadFile, fbDoc, fbAuthReady, fbLoadConfig, fbSaveConfig, fbLoadFamily, fbSaveFamily, fbGenCode, stateToFs, fsToState, FirebaseSetupWizard, FbStatusBadge });

/* =========================================================
   Evidence upload outbox — durable retry queue (IndexedDB)
   Fixes: a failed/timed-out upload used to leave a blob: URL written into
   synced state. blob: URLs die on reload/on any other device, so that
   evidence would silently disappear with no retry and no warning. Now the
   actual file bytes are persisted here, and never referenced by a blob:
   URL in synced Firestore state — evidence.url stays null + pendingUpload:
   true until a real cloud URL exists.
   ========================================================= */
const OUTBOX_DB = 'fw_outbox';
const OUTBOX_STORE = 'pending';
function outboxOpen() {
  return new Promise((resolve, reject) => {
    if (!window.indexedDB) { reject(new Error('IndexedDB not available')); return; }
    const req = indexedDB.open(OUTBOX_DB, 1);
    req.onupgradeneeded = () => {
      if (!req.result.objectStoreNames.contains(OUTBOX_STORE)) {
        req.result.createObjectStore(OUTBOX_STORE, { keyPath: 'key' });
      }
    };
    req.onsuccess = () => resolve(req.result);
    req.onerror = () => reject(req.error);
  });
}
async function outboxPut(entry) {
  const db = await outboxOpen();
  return new Promise((resolve, reject) => {
    const tx = db.transaction(OUTBOX_STORE, 'readwrite');
    tx.objectStore(OUTBOX_STORE).put(entry);
    tx.oncomplete = () => resolve();
    tx.onerror = () => reject(tx.error);
  });
}
async function outboxGetAll() {
  const db = await outboxOpen();
  return new Promise((resolve, reject) => {
    const tx = db.transaction(OUTBOX_STORE, 'readonly');
    const req = tx.objectStore(OUTBOX_STORE).getAll();
    req.onsuccess = () => resolve(req.result || []);
    req.onerror = () => reject(req.error);
  });
}
async function outboxDelete(key) {
  const db = await outboxOpen();
  return new Promise((resolve, reject) => {
    const tx = db.transaction(OUTBOX_STORE, 'readwrite');
    tx.objectStore(OUTBOX_STORE).delete(key);
    tx.oncomplete = () => resolve();
    tx.onerror = () => reject(tx.error);
  });
}
Object.assign(window, { outboxPut, outboxGetAll, outboxDelete });
